title: My Grandpa's Stories
description: placeholder
theme: just-the-docs

url: https://bhmurphy.github.io/my-grandpas-stories/

aux_links:
  View this on GitHub: https://github.com/bhmurphy/my-grandpas-stories.git
